### PR TITLE
update tag interop

### PR DESCRIPTION
**Pull request by Alexander1000**
| Question      | Answer
| ------------- | ------
| Bug fix?      |no
| New feature?  |no
| BC breaks?    | yes
| Deprecations? | yes
| Tests pass?   | yes
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### Description

Update dependencies for use psr/cache last versions

* [x] Updated Changelog.md

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 

Could you please rebase this PR?

**Comment by Nyholm** [comment]
It seams like we need to update dependencies too, right?

**Comment by Alexander1000** [comment]
Yes need. So that you can fully switch to psr/cache of the new version.

**Comment by Nyholm** [comment]
Can we do it in a way that do not break bc? Ie do psr/cache: v1 and v2?

**Comment by Alexander1000** [comment]
but in v1 non strong typing, in v2 strong typing in interfaces
v1: https://github.com/php-fig/cache/blob/1.0.0/src/CacheItemPoolInterface.php#L33
v2: https://github.com/php-fig/cache/blob/2.0.0/src/CacheItemPoolInterface.php#L32

this package (tag interop) in repository extend interfaces

**Comment by ruudk** [comment]
Could something like this help with that?
https://github.com/symfony/phpunit-bridge/blob/15cab721487b7bf43ad545a1e7d0095782e26f8c/SetUpTearDownTrait.php

**Comment by ruudk** [comment]
I see my suggestion is already applied in the PR, ⚡ 
@Nyholm do you think it's a good idea?

**Comment by Nyholm** [comment]
I dropped support for psr/cache:3. That made things much simpler and it will give support for php 8.1 and Symfony 6.

**Comment by Nyholm** [comment]
Thank you Alexander

**Pull request merged**
