### PR TITLE
All components should use the same version

### PR DESCRIPTION
**Pull request by prisis**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? |no
| Tests pass?   | yes
| Fixed tickets | https://github.com/php-cache/issues/issues/47
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
I agree. Will merge when tests are passing.

**Comment by prisis** [comment]
you need to bump phparray to a new version

**Comment by Nyholm** [comment]
Just tagged 0.4.1 on array adapter.

**Comment by Nyholm** [comment]
Packagist lost all versions on https://packagist.org/packages/cache/taggable-cache. I updated the package manually and the versions came back. I've restarted your travis job.

**Pull request merged**
