### PR TITLE
[WIP] Allow php 7.1 in travis

### PR DESCRIPTION
**Pull request by prisis**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| License | MIT |
### Desription

Added support for php 7.1

### CODE REVIEW

**Comment by prisis** [comment]
Any idea why i apc and apcu wont work?

**Comment by Nyholm** [comment]
That's weird. Composer install segfaults. Not too sure why.

**Comment by prisis** [comment]
Maybe a php error...  Ich will check it, if I get the same error on local

**Comment by prisis** [comment]
Ah, I dont habe php7.1 but php7.1beta, maybe the folder name is wrong

**Pull request closed without merging**
