### PR TITLE
[WIP] Put source code at first level folder

### PR DESCRIPTION
**Pull request by maidmaid**
cf php-cache/issues#34

### CODE REVIEW

**Comment by aequasi** [comment]
Is this still [WIP]? I looks good

**Comment by maidmaid** [comment]
@aequasi could you check why tests fail? Imo, it isn't related to my changes.

**Comment by aequasi** [comment]
Its unrelated, is this good otherwise?

**Comment by maidmaid** [comment]
For me, it's :+1:, you can merge this PR. If I forgot something, we can open a new issue.

**Comment by Nyholm** [comment]
Awesome. Thank you!

**Pull request merged**
