### PR TITLE
Add laravel cache bridge

### PR DESCRIPTION
**Pull request by prisis**
| Question      | Answer
| ------------- | ------
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | php-cache/issues#81
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### Description
Add a adapter for laravel cache store

Sorted the composer.json file too.

### TODO
* [x] Add tests
* [ ] Add documentation
* [x] Updated Changelog.md

### CODE REVIEW

**Comment by prisis** [comment]
Hey :), @florianv can you take a look?

**Comment by florianv** [comment]
@prisis Hey, I didn't see your message and just sent an other PR
I just realized you sent one after submiting mine 😫

**Comment by Nyholm** [comment]
Awesome. Thank you both for this. 

Which one should we review and continue working on?

**Comment by prisis** [comment]
Should I close this one?

**Comment by florianv** [comment]
@prisis Yes I think so

In the other PR I didn't implement the `null` trick. It's not required anymore as an array is always stored in the cache (we never store NULL values directly but an array containing NULL)

**Pull request closed without merging**
