### PR TITLE
Travis php72

### PR DESCRIPTION
**Pull request by prisis**
| Question      | Answer
| ------------- | ------
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Alt Text

### Description

Added php 7.2 to travis with a much easier build script (cache is used for pecl for faster build)

Composer dist files are cached
Using the new beta build stages on travis

Ignore the failing build, mongodb and encryption adapter are missing the common adapter

### TODO
* [ ] Add tests
* [ ] Add documentation
* [ ] Updated Changelog.md

### CODE REVIEW

**Comment by prisis** [comment]
The only failing test are mongodb and encryption, because of the missing trait

**Comment by Nyholm** [comment]
Okey, Could you update the version to make sure the trait is found?

**Comment by prisis** [comment]
We need to tag a new version and add it to mongo and encryption

**Comment by prisis** [comment]
But wait a bit before you make a new release, i like to make some bugfixes and small changes

**Comment by Nyholm** [comment]
Okey. So how should we do with this PR now? Is is blocked by fixes on mongo and encryption?

**Comment by prisis** [comment]
Yes and this one https://github.com/php-cache/cache/pull/210 so that we don't have any bugs

I can make a PR for the fix on encryption and mongo, the next version would be 1.1.0?

**Pull request closed without merging**
