### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by Nyholm**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

---

For more information, click [here](https://github.styleci.io/analyses/zOkKDL).

### CODE REVIEW

**Comment by Nyholm** [comment]
FYI @azjezz 

I missed this in my review.

**Comment by azjezz** [comment]
@Nyholm shouldn't then the return type deceleration be `void` instead of `array|null` ?

**Comment by Nyholm** [comment]
You are correct. But this is PHP 5 legacy code.

**Comment by azjezz** [comment]
alright 👍

**Pull request merged**
