### PR TITLE
Fix issues with binary data being stored

### PR DESCRIPTION
**Pull request by StephenClouse**
| Question      | Answer
| ------------- | ------
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

### Description

MongoDB does not accept strings in JSON containing control character bytes (0x00 - 0x1F). These are required to be escaped per the JSON specification (sec. 7). However, these are very easy to create if caching binary data, or serializing PHP objects with non-public properties (the PHP serializer uses the null byte to mark these). This will throw an exception on save with the error "update document contains invalid keys".

This patch escapes the disallowed characters when storing the data in Mongo.

### TODO
* [x] Add tests
* [ ] Add documentation
* [ ] Updated Changelog.md

### CODE REVIEW

**Comment by prisis** [comment]
Thank you for the pr :), can you add a test for this change?

**Comment by Nyholm** [comment]
Yeah, really. This is great! 

Just add a test and we will be happy to merge.

**Comment by StephenClouse** [comment]
Yeah, I'll try to get to it here. We're rapidly iterating on a project and this was a bit of a showstopper.

I feel like any test for this should go into integration-tests, to make sure drivers in general don't have an issue with binary data.

**Comment by StephenClouse** [comment]
I submitted [a separate pull request against integration-tests](https://github.com/php-cache/integration-tests/pull/85) that adds a binary data test.

This pull request now contains fixes for the issues found there: the aforementioned MongoDB adapter, and another bug with the Encryption wrapper (as it uses json_encode internally, it silently fails to store if binary data is passed).

**Comment by prisis** [comment]
Sorry for the late merge of your pr!

But it merged now and a new version is coming soon

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
