### PR TITLE
Hierarchical implementation for Illuminate Adapter

### PR DESCRIPTION
**Pull request by Korbeil**
| Question      | Answer
| ------------- | ------
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | https://github.com/php-cache/documentation/pull/45

### Description

Adding hierarchical implementation to Illuminate Adapter

### TODO
- [x] Add tests
- [x] Add documentation
- [x] Updated Changelog.md

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. This changes looks alright. I'll fix the build errors

**Comment by Nyholm** [comment]
Could you rebase on master so Travis will be happy?

**Comment by Korbeil** [comment]
Done & it looks I've some failures with the Hierarchical implementation.

I'll take a look later to fix thoses ;)

**Comment by Nyholm** [comment]
Excellent. Thank you

**Pull request merged**
