### PR TITLE
Add support laravel 6.0

### PR DESCRIPTION
**Pull request by rez1dent3**
| Question      | Answer
| ------------- | ------
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by rez1dent3** [comment]
php 7.3

branch: `master`
image

my PR:
image

**Comment by ttrig** [comment]
I'm guessing this line needs to be updated?

https://github.com/php-cache/cache/blob/202cd2b3433e5841d822c4a3a24ee20ac656c88d/src/Adapter/Illuminate/IlluminateCachePool.php#L47

https://laravel.com/docs/5.8/upgrade#cache-ttl-in-seconds

**Comment by rez1dent3** [comment]
no longer relevant, sawed out the library and advise others.

**Comment by dinamic** [comment]
@rez1dent3 anything I could help to speed up supporting Laravel 6.x?

**Comment by jkudish** [comment]
FWIW, the only change I needed to make for it to work with my Laravel 6 project was the version bump

**Comment by dinamic** [comment]
Using Symfony's cache adapter worked for me.

**Pull request closed without merging**
