### PR TITLE
Use double pipe in composer json

### PR DESCRIPTION
**Pull request by prisis**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by prisis** [comment]
@Nyholm can i update symfony/cache to use v3.1?

**Comment by aequasi** [comment]
what does double pipe do?

**Comment by aequasi** [comment]
Also, need to resync

**Comment by prisis** [comment]
@aequasi  https://getcomposer.org/doc/articles/versions.md

**Comment by aequasi** [comment]
Both work, apparently this is the new standard :)

**Pull request merged**
