### PR TITLE
Added new package TagInterop

### PR DESCRIPTION
**Pull request by Nyholm**
I decided to put the interfaces in a separate package. 

I would like to merge this and make a version 1.0 of this package. 

Ping @php-cache/featured-users and @nicolas-grekas: What do you think about the interfaces? Can I get your final thumbs up?

When this is merged, these are the interfaces I will write a PSR for

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
LGTM. Of course, we may gather more feedback when going to he FIG so things may change then.

**Comment by prisis** [comment]
Looks good :+1:

**Comment by Nyholm** [comment]
Thank you. 
I want to avoid BC breaking changes though...

**Comment by rvanlaak** [comment]
Interfaces look good 👍

**Comment by Nyholm** [comment]
Thank you for the feedback

**Pull request merged**
