### PR TITLE
Fix master

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by Nyholm** [comment]
The `cache/integration-tests: ^0.17` came with [a few new tests](https://github.com/php-cache/integration-tests/compare/0.16.0...0.17.0). Ie when you use way too long keys. That is not supported hence the test failed. 

This PR does not aim to add support for 300 char long keys. 

I also dropped >7.4

**Comment by Nyholm** [comment]
@ruudk could you confirm this PR?

**Comment by ruudk** [comment]
Looks good! Thanks for fixing it.

**Comment by Nyholm** [comment]
Thank you for your work!

**Comment by ruudk** [comment]
I'll give it a final test tomorrow, before you tag the release

**Comment by ruudk** [comment]
Seems to work fine, tag it :shipit:  😊

**Pull request merged**
