### PR TITLE
Added support for simple cache

### PR DESCRIPTION
**Pull request by Nyholm**
| Question      | Answer
| ------------- | ------
| Bug fix?      | yes (included a bugfix)
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

### Description

This will add support for simple cache. Im just waiting for a new version of the integration tests atm. 

### TODO
* [x] Add tests
* [ ] Add documentation
* [ ] Updated Changelog.md

### CODE REVIEW

**Comment by prisis** [comment]
Love this :), no need for the SimpleCacheBridge

**Comment by Nyholm** [comment]
The simple cache bridge is still great for converting **any** PSR6 to SimpleCache.

**Comment by prisis** [comment]
Then the doctrine bridge need support for simple cache too?

**Comment by Nyholm** [comment]
Yes, Or you could wrap the doctrine bridge into the SimpleCache bridge and you've solved the issue.

**Comment by prisis** [comment]
Ort this :)

**Comment by Nyholm** [comment]
Im merging this because the failed tests is not related.

**Pull request merged**
