### PR TITLE
Fix missing tag warning error

### PR DESCRIPTION
**Pull request by julien-maitan**
| Question      | Answer
| ------------- | ------
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

### Description
I'm using the Symfony bundle with this configuration:

```
cache_adapter:
  providers:
    api_redis1:
      factory: 'cache.factory.predis'
      options:
        dsn: "%redis_dsn%"
        pool_namespace: "%mall_reference%_website"
      aliases: ['cache.api_redis1']
    api_redis2:
      factory: 'cache.factory.predis'
      options:
        dsn: "%redis2_dsn%"
        pool_namespace: "%mall_reference%_website"
      aliases: ['cache.api_redis2']
    api_array:
      factory: "cache.factory.array"
      options:
        pool_namespace: "%mall_reference%_website"
      aliases: ["cache.api_array"]
    api:
      factory: "cache.factory.chain"
      options:
        services:
          - '@cache.api_array'
          - '@cache.api_redis1'
          - '@cache.api_redis2'
        skip_on_failure: true
      aliases: ["cache.api"]
```

When the redis cache is available, I get those errors

```
( ! ) Notice: Undefined index: tag!page in vendor/cache/array-adapter/ArrayCachePool.php on line 200
--
1 | 0.0002 | 250272 | {main}(  ) | .../app.php:0
2 | 0.0779 | 1756040 | Symfony\Component\HttpKernel\Kernel->handle(  ) | .../app.php:18
3 | 0.3354 | 5658032 | Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(  ) | .../bootstrap.php.cache:1505
4 | 0.3355 | 5659288 | Symfony\Component\HttpKernel\HttpKernel->handle(  ) | .../ContainerAwareHttpKernel.php:69
5 | 0.3355 | 5660240 | Symfony\Component\HttpKernel\HttpKernel->handleRaw(  ) | .../HttpKernel.php:64
6 | 0.5733 | 8108848 | call_user_func_array:{vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144} (  ) | .../HttpKernel.php:144
7 | 0.5733 | 8109728 | AppBundle\Controller\DefaultController->indexAction(  ) | .../HttpKernel.php:144
8 | 0.7872 | 10893728 | AppBundle\Provider\ContentProvider->getStructBySlug(  ) | .../DefaultController.php:143
9 | 0.7872 | 10894512 | AppBundle\Provider\ContentProvider->getApiData(  ) | .../ContentProvider.php:176
10 | 0.7872 | 10894760 | Cache\Adapter\Chain\CachePoolChain->getItem(  ) | .../ContentProvider.php:219
11 | 0.8431 | 11034816 | Cache\Namespaced\NamespacedCachePool->save(  ) | .../CachePoolChain.php:89
12 | 0.8431 | 11035008 | Cache\Adapter\Common\AbstractCachePool->save(  ) | .../NamespacedCachePool.php:129
13 | 0.8431 | 11035088 | Cache\Adapter\Common\AbstractCachePool->removeTagEntries(  ) | .../AbstractCachePool.php:228
14 | 0.8431 | 11036072 | Cache\Adapter\PHPArray\ArrayCachePool->removeListItem(  ) | .../AbstractCachePool.php:409


( ! )  Warning: Invalid argument supplied for foreach() in vendor/cache/array-adapter/ArrayCachePool.php  on line 200
--
1 | 0.0002 | 250272 | {main}(  ) | .../app.php:0
2 | 0.0779 | 1756040 | Symfony\Component\HttpKernel\Kernel->handle(  ) | .../app.php:18
3 | 0.3354 | 5658032 | Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(  ) | .../bootstrap.php.cache:1505
4 | 0.3355 | 5659288 | Symfony\Component\HttpKernel\HttpKernel->handle(  ) | .../ContainerAwareHttpKernel.php:69
5 | 0.3355 | 5660240 | Symfony\Component\HttpKernel\HttpKernel->handleRaw(  ) | .../HttpKernel.php:64
6 | 0.5733 | 8108848 | call_user_func_array:{vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144} (  ) | .../HttpKernel.php:144
7 | 0.5733 | 8109728 | AppBundle\Controller\DefaultController->indexAction(  ) | .../HttpKernel.php:144
8 | 0.7872 | 10893728 | AppBundle\Provider\ContentProvider->getStructBySlug(  ) | .../DefaultController.php:143
9 | 0.7872 | 10894512 | AppBundle\Provider\ContentProvider->getApiData(  ) | .../ContentProvider.php:176
10 | 0.7872 | 10894760 | Cache\Adapter\Chain\CachePoolChain->getItem(  ) | .../ContentProvider.php:219
11 | 0.8431 | 11034816 | Cache\Namespaced\NamespacedCachePool->save(  ) | .../CachePoolChain.php:89
12 | 0.8431 | 11035008 | Cache\Adapter\Common\AbstractCachePool->save(  ) | .../NamespacedCachePool.php:129
13 | 0.8431 | 11035088 | Cache\Adapter\Common\AbstractCachePool->removeTagEntries(  ) | .../AbstractCachePool.php:228
14 | 0.8431 | 11036072 | Cache\Adapter\PHPArray\ArrayCachePool->removeListItem(  ) | .../AbstractCachePool.php:409
```

### CODE REVIEW

**Comment by Nyholm** [comment]
Will this issue be the same for other adapters?

**Comment by julien-maitan** [comment]
I'm actually using only a few adapters (chain, array, predis), but after a quick look at code, I don't think this issue can impact other adapters, because they either use TagSupportWithArray trait, either implements a getList method which return an empty array if nothing matches.

And while writing this comment, I just realize that array-adapter also has the getList method which do the exact same test and return an empty array ! So I will update my pull request.

**Comment by prisis** [comment]
@julien-maitan can you add a test for this?`
so that i can merge this

**Comment by julien-maitan** [comment]
@prisis I tried but I don't know how to reproduce this behavior with ArrayCachePool only. And obviously, I don't know how to assert there is no Notice error.

**Comment by prisis** [comment]
Hey :), some infos how to do it https://stackoverflow.com/questions/5053914/how-to-catch-php-warning-in-phpunit

**Comment by julien-maitan** [comment]
So you want me to write a test that can catch the notice error fixed with my pull request?

**Comment by prisis** [comment]
Yes :) if you can

**Comment by julien-maitan** [comment]
You are kidding me,  right?

**Comment by aequasi** [comment]
That's kinda the point of testing. If we have a test, we know it wont happen in the future for some unknown reason.

**Comment by julien-maitan** [comment]
After a few googling, I found https://github.com/sebastianbergmann/phpunit-documentation/issues/171 and the final comment point me to the way, https://stackoverflow.com/questions/28661339/phpunit-how-to-test-if-method-does-nothing/45850982#45850982.

**Comment by prisis** [comment]
Thanks for your work :)

**Comment by julien-maitan** [comment]
You're welcome. And sorry for misunderstanding your point on the exception.

**Pull request merged**
