### PR TITLE
Storing items into previous cache pool

### PR DESCRIPTION
**Pull request by panki3a**
add storing items into previous cache pool in getItems method

| Question      |  Answer
| ------------ | ------ |
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Tests pass?   | yes/no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### TODO
* [ ] Add tests
* [ ] Add documentation
* [ ] Updated Changelog.md

### CODE REVIEW

**Comment by Nyholm** [comment]
Does this PR replace #157?

**Comment by panki3a** [comment]
yes,

**Comment by Nyholm** [comment]
Okey, great. But it is the same thing here. Make sure to add a test and that StyleCI is green

**Comment by panki3a** [comment]
but i can't write the test, i have no idea, how to do that

**Comment by Nyholm** [comment]
You can add a new tests in src/Adapter/Chain/Tests.php. 

You can create 2 array adapters and fill them with some values. Then put them in the chain, then can test if the chain behaves like you expect.

**Comment by prisis** [comment]
Hey :), nice work!, can you add a test for the Exception, where handleException is called?

**Pull request merged**
